{{- if .Values.ingress.basicAuth.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.ingress.basicAuth.secretName }}
data:
  auth: {{ .Values.ingress.basicAuth.secretHash }}
{{- end }}