apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: clusterchat-ingress
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx

    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    
    # type of authentication [basic|digest]
    # nginx.ingress.kubernetes.io/auth-type: basic
    # nginx.ingress.kubernetes.io/auth-secret: myauthsecret
    # nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: {{ .Values.webapp.port }}
      - path: /ws
        backend:
          serviceName: server
          servicePort: {{ .Values.server.port }}
