version: '3'

services:
  redis:
    image: redis:alpine
    expose:
      - "6379"
  nginx:
    depends_on:
      - server-one
      - server-two
      - server-three
      - server-four
    build: ./nginx
    ports:
      - "80:80"

  server-webapp:
    build: ./webapp
    expose:
      - "3001"
    environment:
      - PORT=3001

  server-one:
    build: ./server
    depends_on:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=one
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  server-two:
    depends_on:
      - redis
    build: ./server
    expose:
      - "3000"
    environment:
      - NAME=two
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  server-three:
    depends_on:
      - redis
    build: ./server
    expose:
      - "3000"
    environment:
      - NAME=three
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  server-four:
    depends_on:
      - redis
    build: ./server
    expose:
      - "3000"
    environment:
      - NAME=four
      - REDIS_HOST=redis
      - REDIS_PORT=6379


