apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: clusterchat-ingress
  annotations:
    # nginx.org/websocket-services: "server"
    # nginx.ingress.kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
  - host: dev.dolph
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: 3001
      - path: /test
        backend:
          serviceName: webapp
          servicePort: 3001
      - path: /ws
        backend:
          serviceName: server
          servicePort: 3000
      # - path: /api
      #   backend:
      #     serviceName: api
      #     servicePort: 3000
      