apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: clusterchat-ingress
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx

    # Not working as expected
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # ingress.kubernetes.io/add-base-url: true
    
    # type of authentication [basic|digest]
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: myauthsecret
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
  - host: chat.dev.dolph
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: 3001
      - path: /test
        backend:
          serviceName: webapp
          servicePort: 3001
      - path: /ws
        backend:
          serviceName: server
          servicePort: 3000
      # - path: /api
      #   backend:
      #     serviceName: api
      #     servicePort: 3000
      