apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: clusterchat-server
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: clusterchat-server
    spec:
      containers:
      - name: clusterchat-server
        image: dolphub/clusterchat-server:0.1.1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: "redis-master"
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: clusterchat-server