apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: clusterchat-server
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: clusterchat-server
    spec:
      containers:
      - name: clusterchat-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: "{{ .Release.Name }}-redis"
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: clusterchat-server