######
# TODO: Set up TLS
######

webapp:
  replicaCount: 2

server:
  replicaCount: 5

redis:
  usePassword: false

ingress:
  host: chat.dev.dolph
  basicAuth:
    enabled: false
    secretName: myauthsecret
    secretHash: YWRtaW46JGFwcjEkZzNsTVdubzUkT1Flb1ZucnF6NGlRamRYc1JrT2c3MQ==

